name: Auto Commit

on:
  schedule:
    - cron: "0 1 * * *"
    - cron: "0 3 * * *"
    - cron: "0 5 * * *"
    - cron: "0 7 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Update LAST_UPDATED
        run: |
          date -u '+%Y-%m-%dT%H:%M:%SZ' > LAST_UPDATED

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add LAST_UPDATED

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "chore(bot): auto commit"

      - name: Sync and Push changes
        run: |
          git pull --rebase origin master
          git push origin master
